### ISSUE TITLE
Pre-request Script doesn't handle host name with dashes correctly

### ISSUE THREAD

**Issue by di9383-zz** [MicrosoftCSA/cosmosdb-postman-collection#1]
Hi.
I have an issue with the host name. If host name has "-" in its name, for instance "https://some-uri-name-here.documents.azure.com:443" {{authToken}} is not populated.
Update:
Looking in the console output I see, that {{authToken}} is being populated, but a response on any request is:
Entity with the specified id does not exist in the system.
 ActivityId: 5625d3b3-a13f-41ef-95ee-000000000000, Microsoft.Azure.Documents.Common/2.0.0.0

If I use CosmosDb account without dashes in the account name everything works fine. Not sure where to look at for handling this error, because a console output in both cases are seems to be the same - all variables are there. It might be some Postman issue with dashes as well, I believe.
Any help is much appreciated.

**Comment by ameesh1984** [comment]
Was this resolved ?
