### ISSUE TITLE
Postman Collection Format v1 is no longer supported and can not be imported directly

### ISSUE THREAD

**Issue by gurdeepbhatia** [MicrosoftCSA/cosmosdb-postman-collection#3]
![image](https://user-images.githubusercontent.com/65391124/124757705-7c8ba580-df4b-11eb-9478-752961b57c8f.png)

**Comment by Aionsphere** [comment]
This is now resolved.

**Comment by Aionsphere** [comment]
Converted to v2.1 format with pretty formatting and renamed as CosmosDB. Also moved the pre-request script to the collection level.
